remote_theme: zendesk/jekyll-theme-zendesk-garden@main

search_enabled: true

sidebar:
  - home
  - quick_start
  - installation
  - module_overview
  - label: Command-line manual
    children:
      - generate_alignments
      - chain_self_alignments
      - chain_alignments
      - visualize_chains
      - fetch_nucleotide_chains
  - app
  - docker
  - citation
  - feedback