remote_theme: zendesk/jekyll-theme-zendesk-garden@main

search_enabled: true
auto_page_title: true

sidebar:
  - home
  - manual
  - quick_start
  - installation
  - module_overview
  - label: command_line_manual
      - generate_alignments
      - chain_self_alignments
      - chain_alignments
      - visualize_chains
      - fetch_nucleotide_chains
  - app
  - docker
  - citation
  - feedback